extends: default

ignore: |
  target/
  dbt_packages/

rules:
  line-length:
    max: 250
  document-start: disable
  truthy:
    check-keys: false   # GitHub Actions uses `on:`
  braces:
    max-spaces-inside: 1
  comments:
    min-spaces-from-content: 1
