default:
  target: ci
  outputs:
    ci:
      type: duckdb
      path: target/ci.duckdb
      schema: analytics
      threads: 1
    demo:
      type: duckdb
      path: target/demo.duckdb
      schema: analytics
      threads: 1
